version: 2

registries:
  github-npm:
    type: npm-registry
    url: https://npm.pkg.github.com
    username: x-access-token
    password: ${{secrets.DEPENDABOT_GITHUB_PACKAGES_TOKEN}}

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "chore(deps)"

  - package-ecosystem: "npm"
    directory: "/"
    registries:
      - github-npm
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:15"
      timezone: "Europe/Berlin"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "chore(deps)"
    versioning-strategy: auto
