baseURL = "https://eskyna.com/"
defaultContentLanguage = "de"
defaultContentLanguageInSubdir = false
disableHugoGeneratorInject = true
cleanDestinationDir = true
[minify]
  minifyOutput = true
title = "Natalia Kleemann | Style & Image Coaching Vor-Ort & Online"

[languages]
  [languages.de]
    title = "Natalia Kleemann | Style & Image Coaching Vor-Ort & Online"
    locale = "de-DE"
    languageName = "Deutsch"
    weight = 1
    contentDir = "content/de"
    [languages.de.params]
      author = "Natalia Kleemann"
      description = "Persönliches Style- und Image-Coaching Vor-Ort und Online. Entdecken Sie Ihren individuellen Stil, treten Sie sichtbar und authentisch auf. ESKYNA begleitet Sie zu mehr Stilsicherheit und Selbstvertrauen."
  
  [languages.ru]
    title = "Natalia Kleemann | Имидж- и стиль-коучинг онлайн и в Ганновере"
    locale = "ru-RU"
    languageName = "Русский"
    weight = 2
    contentDir = "content/ru"
    [languages.ru.params]
      author = "Natalia Kleemann"
      description = "Персональный имидж- и стиль-коучинг в Ганновере и онлайн. Развивайте свой стиль, уверенность и аутентичность с методом ESKYNA. Трансформируйте образ и становитесь заметным, стильным и уверенным профессионалом."

[params]
  author = "Natalia Kleemann"
  description = "Persönliches Style- und Image-Coaching Vor-Ort und Online. Entdecken Sie Ihren individuellen Stil, treten Sie sichtbar und authentisch auf. ESKYNA begleitet Sie zu mehr Stilsicherheit und Selbstvertrauen."
  keywords = "Styleberatung, Imageberatung, Personal Styling, Farbberatung, Hannover, Online Coaching"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
